### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by deedeeharris** [Valentin-Metz/tum_video_scraper#16]
Can I use this with https://huji.cloud.panopto.eu/ ?

Thanks.

**Comment by Valentin-Metz** [comment]
You can adapt the panopto downloader for that with little effort.
This function should be all you need to change:
https://github.com/Valentin-Metz/tum_video_scraper/blob/master/src/panopto.py#L13

**Comment by deedeeharris** [comment]
Thanks for the quick response.
You mean replace every tum with huji?

Does this script worth headless?
