### ISSUE TITLE
Config file 

### ISSUE THREAD

**Issue by kaantureyyen** [Valentin-Metz/tum_video_scraper#17]
Mooiin,
I can not seem to get the argparse to parse my yml config file. Using a windows machine and running the docker image, I go
`docker run tum_video_scraper -c .\[some_yml.yml]`
What am I missing here? :(

**Comment by Valentin-Metz** [comment]
Make sure to mount the file you want to access into the container, as described here: https://docs.docker.com/storage/volumes/

**Comment by kaantureyyen** [comment]
Aah I see, but even if I don't want to supply a config file and only use terminal arguments, I still get the same error message :(

![image](https://github.com/Valentin-Metz/tum_video_scraper/assets/45270507/533d9629-cb50-4169-8f40-033d3b2b1680)

**Comment by kaantureyyen** [comment]
got it to run with the config file mounted, still confused about how to run it with command line variables
