### ISSUE TITLE
Can't find videos with new format?

### ISSUE THREAD

**Issue by JGStyle** [Valentin-Metz/tum_video_scraper#19]
Maybe im just not passing the url the right way but I get

```
Starting new run!

Scanning TUM-live:
Found 0 videos for "analysis"

--------------------

Starting downloads:
```
no matter what I do
here is the command I execute

`python ./src/main.py --output_folder /Users/jgs/Developer/Spielplatz/tum_video_scraper/out --tum_live analysis:anainfo/37199:CAM
`

I also tried this

`python ./src/main.py --output_folder /Users/jgs/Developer/Spielplatz/tum_video_scraper/out --tum_live analysis:w/anainfo/37199:CAM
`

but same results,
I also tried this

`python ./src/main.py --output_folder /Users/jgs/Developer/Spielplatz/tum_video_scraper/out --tum_live analysis:2023/w/anainfo/37199:CAM
`

again, same thing

I looked into the main.py and I found some parts referencing the new layout with /w/ however I can not get it to find the vids. I have also tried it with different courses, but I get the same

thanks for the project, I hope you can help!

**Comment by JGStyle** [comment]
note, I also did provide the flags --username and --password for authentication

**Comment by Valentin-Metz** [comment]
For now, please use the URL you get on the "old" TUM-live design URL, [until a stable API is implemented](https://github.com/TUM-Dev/gocast/issues/748).
In your case this would be https://live.rbg.tum.de/old/course/2023/W/anainfo, with `2023/W/anainfo` as selector.

**Comment by Valentin-Metz** [comment]
I've provided updated documentation that should make it more clear how to find these in the future.
