### ISSUE TITLE
Feat request: split version

### ISSUE THREAD

**Issue by euberdeveloper** [Valentin-Metz/tum_video_scraper#21]
There is on TUM live also the SPLIT view, but it is missing in the scarper

**Comment by Valentin-Metz** [comment]
The "Splitview" is not a combined rendered video, but two videos (`cam`+`pres`) being played side by side in your browser.
Both are rendered independently, therefore they do not have a single videostream that can be downloaded by us.
If you want to reproduce this view, simply download both the `pres` and the `cam` view, and play them side-by-side.
