### ISSUE TITLE
auto_editor.wavfile.WavError: File format b'' not supported.

### ISSUE THREAD

**Issue by AntonMC-Github** [Valentin-Metz/tum_video_scraper#24]
Servus, vielleicht könnt ihr mir weiterhelfen:

Ich habe gerade versucht eine Vorlesung herunterzuladen und dabei den folgenden Error bekommen (Ich habe die konkrete Vorlesung mal zur Sicherheit rausgenommen). Habe ich da selbst einen Fehler gemacht oder hat sich da auf TUM.Live Seite was am Codec / Dateibennennung etc. geändert?

Error during conversion of "002_Lecture__April_23._2024.mp4" with auto-editor:
Playlist file: LINK TO PLAYLIST FILE
Designated output location: /app/output/VORLESUNGSKÜRZEL/002_Lecture__April_23._2024_jc.mp4
Output of auto-editor to stdout:
  ⏳Creating new audio |███████████████████▎          | 64.4%  ETA 09:53 AM    
Output of auto-editor to stderr:
Traceback (most recent call last):
  File "/usr/local/bin/auto-editor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/auto_editor/__main__.py", line 332, in main
    edit_media(paths, ffmpeg, args, temp, log)
  File "/usr/local/lib/python3.12/site-packages/auto_editor/edit.py", line 359, in edit_media
    make_media(tl, output)
  File "/usr/local/lib/python3.12/site-packages/auto_editor/edit.py", line 290, in make_media
    audio_output = make_new_audio(tl, ensure, args, ffmpeg, bar, temp, log)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/auto_editor/render/audio.py", line 251, in make_new_audio
    clip_arr = read(f"{af_out}")[1]
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/auto_editor/wavfile.py", line 201, in read
    raise WavError(f"File format {file_sig!r} not supported.")
auto_editor.wavfile.WavError: File format b'' not supported.

Das ist meine Config:
TUM-live:
  "VORLESUNGSKÜRZEL": "2024/S/VORLESUNGSNAME:COMB"

Username: "USERNAME"
Password: "PASSWORD"

Keep-Original-File: true
Jumpcut: true

Output-Folder: "/app/output"

Maximum-Parallel-Downloads: 3

Ich habe das ganze als Dockercontainer mit folgendem Befehl ausgeführt:
`docker run -it -v /root/config.yml:/app/config.yml -v /app/output:/app/output ghcr.io/valentin-metz/tum_video_scraper:master`

Vielen Dank euch schon Mal für die Zeit und das geniale Tool!

**Comment by Valentin-Metz** [comment]
Ist das reproduzierbar? - Also wenn du das lock-file der Datei löschst und das ganze neu startest, tritt der Fehler erneut auf?
Funktioniert das herunterladen der anderen Vorlesungen aus der Vorlesungsreihe?

**Comment by Valentin-Metz** [comment]
I'm gonna assume this is fixed / has not reoccurred and close the issue. If it persists, feel free to open a new issue.
